# Generated by Django 3.1.2 on 2021-04-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newname', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='chikaku',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='name',
            name='gaikaku',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='name',
            name='jinkaku',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='name',
            name='kateiun',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='name',
            name='shigotoun',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='name',
            name='soukaku',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='name',
            name='tenkaku',
            field=models.IntegerField(default=0),
        ),
    ]
