# Generated by Django 3.1.2 on 2021-04-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newname', '0002_auto_20210411_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='sex',
            field=models.CharField(default='男性', max_length=4),
            preserve_default=False,
        ),
    ]
