# Generated by Django 3.1.2 on 2021-04-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newname', '0003_name_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanjidata',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('figure', models.TextField(blank=True, null=True)),
                ('stroke', models.IntegerField(blank=True, null=True)),
                ('joyo', models.IntegerField(blank=True, null=True)),
                ('jinmeiyo', models.IntegerField(blank=True, null=True)),
                ('kana', models.IntegerField(blank=True, null=True)),
                ('kigou', models.IntegerField(blank=True, null=True)),
                ('reading_onyomi', models.TextField(blank=True, null=True)),
                ('reading_kunyomi', models.TextField(blank=True, null=True)),
                ('mean', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kanjidata',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='name',
            old_name='sex',
            new_name='sex_text',
        ),
        migrations.RemoveField(
            model_name='name',
            name='chikaku',
        ),
        migrations.RemoveField(
            model_name='name',
            name='gaikaku',
        ),
        migrations.RemoveField(
            model_name='name',
            name='jinkaku',
        ),
        migrations.RemoveField(
            model_name='name',
            name='kateiun',
        ),
        migrations.RemoveField(
            model_name='name',
            name='shigotoun',
        ),
        migrations.RemoveField(
            model_name='name',
            name='soukaku',
        ),
        migrations.RemoveField(
            model_name='name',
            name='tenkaku',
        ),
    ]
