# Generated by Django 3.1.2 on 2021-05-08 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newname', '0004_auto_20210422_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameLparam',
            fields=[
                ('name_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='newname.name')),
            ],
            options={
                'managed': False,
            },
            bases=('newname.name',),
        ),
        migrations.CreateModel(
            name='NameLstroke',
            fields=[
                ('name_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='newname.name')),
            ],
            options={
                'managed': False,
            },
            bases=('newname.name',),
        ),
        migrations.CreateModel(
            name='FortuneTelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, null=True)),
                ('stroke', models.IntegerField(blank=True, null=True)),
                ('luck', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fortunetelling',
            },
        ),
        migrations.AlterModelOptions(
            name='kanjidata',
            options={},
        ),
    ]
