# Generated by Django 3.1.2 on 2021-05-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newname', '0005_auto_20210509_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanjidata',
            name='n_impression_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='kanjidata',
            name='p_impression_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='kanjidata',
            name='search_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
